# Generated by Django 2.1.7 on 2019-03-17 14:53

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('about_p', models.TextField(blank=True)),
                ('about_skill_web_development_col_one', wagtail.core.fields.RichTextField(blank=True)),
                ('about_skill_web_development_col_two', wagtail.core.fields.RichTextField(blank=True)),
                ('about_skill_digital_marketing', wagtail.core.fields.RichTextField(blank=True)),
                ('about_skill_web_analytics_col_one', wagtail.core.fields.RichTextField(blank=True)),
                ('about_skill_web_analytics_col_two', wagtail.core.fields.RichTextField(blank=True)),
                ('about_skill_data_science_col_one', wagtail.core.fields.RichTextField(blank=True)),
                ('about_skill_data_science_col_two', wagtail.core.fields.RichTextField(blank=True)),
                ('about_education', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
